spring:
  application:
    name: fin-track
  datasource:
    url: jdbc:postgresql://localhost:5432/fin-track
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: db/changelog/master.yaml
    enabled: true
  security:
    user:
      name: admin
      password: admin

true:
  layer:
    client:
      id: sandbox-demoapp-63cf39
    redirect:
      uri: "https://f278-193-180-91-234.ngrok-free.app/callback"
      page: "https://console.truelayer.com/redirect-page"
    scope: "verification"
