spring:
  application:
    name: fin-track
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: db/changelog/master.yaml
    enabled: true
  security:
    user:
      name: admin
      password: admin
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: fin-track-group
      auto-offset-reset: earliest
    producer:
      retries: 3

truelayer:
  scope: "accounts%20transactions"