spring:
  application:
    name: fin-track
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: db/changelog/master.yaml
    enabled: true
  security:
    user:
      name: admin
      password: admin

truelayer:
  scope: "accounts%20transactions"